"""init schema

Revision ID: 6a4bf82aeb8e
Revises: 
Create Date: 2026-05-23 05:41:14.970243

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision = '6a4bf82aeb8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enquiries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('whatsapp', 'email', 'call', name='channelenum'), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'matched', 'escalated', 'followup_scheduled', 'closed', name='enquirystatusenum'), nullable=False),
    sa.Column('matched_sop', sa.String(length=200), nullable=True),
    sa.Column('suggested_response', sa.Text(), nullable=True),
    sa.Column('escalation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('enquiry_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('created', 'sop_matched', 'escalated', 'followup_scheduled', 'followup_triggered', name='eventtypeenum'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('followups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('enquiry_id', sa.UUID(), nullable=False),
    sa.Column('delay_minutes', sa.Integer(), nullable=False),
    sa.Column('template', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'sent', 'cancelled', name='followupstatusenum'), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followups')
    op.drop_table('events')
    op.drop_table('enquiries')
    # ### end Alembic commands ###
